* Peer Down: modified reason code with optional TLV field.
TimEvens/draft-ietf-grow-bmp-loc-rib pull request #11
Opened 2019-02-14 12:12 UTC by paololucente

2019-02-15 05:56 UTC, TimEvens requested changes
Looks good, but this change should be in the XML file.  The TXT can then be generated.  Normally I update the XML then generate the text.

2019-02-15 05:56 UTC, TimEvens commented on draft-ietf-grow-bmp-local-rib.txt
> +   o  Type = TBD4: VRF/Table Name.  The Information field contains an
VRF Table name is **TBD2**.

2019-02-15 05:56 UTC, TimEvens commented on draft-ietf-grow-bmp-local-rib.txt
> +   Peer down notification SHOULD use reason code TBD3. Following the
TBD3 needs to be added to IANA considerations as well.

2019-02-15 14:17 UTC, paololucente commented
Thank you @TimEvens for the review and guidance. I should have taken into account all your comments with the second commit.

2019-02-20 03:32 UTC, TimEvens commented on draft-ietf-grow-bmp-local-rib.txt
> +   Peer down notification SHOULD use reason code TBD3. Following the
Looks good

2019-02-20 03:32 UTC, TimEvens approved these changes

2019-02-20 03:32 UTC, merged