Intoduced V flag for cases in which Peer Address is non zero filled.
TimEvens/draft-ietf-grow-bmp-loc-rib pull request #17
Opened 2019-11-01 03:02 UTC by paololucente

2019-11-02 00:06 UTC, TimEvens requested changes
I'm still on the fence of actually needing the peer address non-zero...

```
The remote IP address associated with the TCP
      session over which the encapsulated PDU was received.
```

This is a bit misleading as the PDU is supposed to be originated by the local instance. It is only an address of the router itself and never a BGP peer remote IP. It needs to be consistent, so rather than use loopback which is not consistent across implements, zero-filled is better. 

I see that the peer address had to be added to RFC7854 in order to support the multiplexing of PDU's. Local rib needs this too.  Different topologies/instances are supposed to be represented by VRF and/or distinguisher, which is called out. 

I don't recall the exact reason why you added remote ip, but we should have challenged the update for it. I believe the use-case to add remote-ip is only adding value to detect which peer the route came from. Maybe for stats on which peer is used more often and/or troubleshooting....   Regardless, ingress added communities can be used for this purpose.

Sending local-rib to the BMP receiver is highly likely to be over the same BMP session that is used for monitoring BGP adj-rib-in/out.   Right now, the per-peer header fields (type, peer address, peer distinguisher, peer as, bgp-id) uniquely identify the peer.  Hashing these values serve as a peer ID, which right now represents a PEER_UP and therefore RIB topology.  Changing this to have variable peer addresses that actually is for the same RIB means that the receiver now has to change to not include the peer address in the hashing/identification when processing the per-peer header when the type is loc-rib.  This is a larger change than what was called out.  

While from a single app perspective, this doesn't sound like an issue, but considering it changes the logic for distributed BMP receivers where the ingress BMP receiver is a forwarder for workers that handle the heavy lifting.  For example, receive all incoming BMP messages and route them to topic partitions (e.g., kafka) in receive FIFO order.  Order obviously is important for processing the "RIB".  Changing flags is one thing... but changing how the receiver hashes/ids the "peer/rib" is a bit more involved.  The current 7854, adr-rib-out, and loc-rib were not intended to change the behavior of how the receiver identifies/demultiplexes the stream of PDU's to RIB's that must be processed in receive order.

Anyhow, my thoughts are to update this to revert it back to zero-filled and then add a note to other considerations to document how one can use communities to identify where routes came from.  This method is also better in terms of supporting non IPv4/IPv6 added routes (static, distributed, imported, ...).  If we do have to stick with adding remote IP's, then IMO, we need to clarify that we are changing/updating RFC7854 in how a receiver uniquely identifies a multiplex stream, when the type is 3.

2019-11-02 00:06 UTC, TimEvens commented on draft-ietf-grow-bmp-local-rib.txt
> +                             |V|F| Reserved  |
While V is flag 0 in RFC7854, flags are called out as being specific to peer type. As to avoid confusion, the flag ordering should not be assumed to match RFC7854 as that will cause other issues, such as the F flag being 1 which in RFC7854 is L.

2019-11-02 00:06 UTC, TimEvens commented on draft-ietf-grow-bmp-local-rib.txt
> +   o  Flag 1: F flag
I suppose if IANA doesn't care to have to lookup the flag description, it's fine to remove it... but it's inconsistent with 8.1 and 8.3 where they are defined/detailed.

2019-11-04 03:32 UTC, paololucente reviewed
Hi Tim,

Thank you for the very detailed review, appreciated it very much. While i do think (for an implementation supporting such functionality) being able to identify which peer announcement made it to Loc-Rib is a valid idea, i agree with your "This is a bit misleading as the PDU is supposed to be originated by the local instance" point. This makes me think this specific exercise must be seen from a different perspective.

With https://www.ietf.org/id/draft-ietf-grow-bmp-tlv-01.txt we are introducing TLVs as part of the Route Monitoring message. Perhaps some optional TLV to be defined in a separate draft would be the best way forward. On a tangent, the same exercise may apply to Adj-RIB-Out thus establishing a full link among what is received and what is advertised. 

Now, concretely, i would: 1) close this PR and 2) roll back commit 28897e9fa51352b07a607dc39cc5d512974bad21 so that we remove the reference to an unexisting 'V flag'.

Paolo

2019-11-04 03:33 UTC, closed without merging